"""
FinLake — reference data for the Bronze ingestion pipeline.

NSE_TICKERS is the source of truth for which tickers this pipeline pulls and
what metadata backs `dim_tickers`. yfinance requires an exchange suffix on
Indian symbols (.NS for NSE, .BO for BSE) — the base `ticker` field is what
appears in Iceberg tables and dashboards; `yfinance_symbol` is only used when
calling the yfinance API.
"""

NSE_TICKERS = [
    {"ticker": "RELIANCE",   "company_name": "Reliance Industries Ltd",         "exchange": "NSE", "yfinance_symbol": "RELIANCE.NS"},
    {"ticker": "TCS",        "company_name": "Tata Consultancy Services Ltd",   "exchange": "NSE", "yfinance_symbol": "TCS.NS"},
    {"ticker": "HDFCBANK",   "company_name": "HDFC Bank Ltd",                   "exchange": "NSE", "yfinance_symbol": "HDFCBANK.NS"},
    {"ticker": "ICICIBANK",  "company_name": "ICICI Bank Ltd",                  "exchange": "NSE", "yfinance_symbol": "ICICIBANK.NS"},
    {"ticker": "INFY",       "company_name": "Infosys Ltd",                     "exchange": "NSE", "yfinance_symbol": "INFY.NS"},
    {"ticker": "HINDUNILVR", "company_name": "Hindustan Unilever Ltd",          "exchange": "NSE", "yfinance_symbol": "HINDUNILVR.NS"},
    {"ticker": "ITC",        "company_name": "ITC Ltd",                         "exchange": "NSE", "yfinance_symbol": "ITC.NS"},
    {"ticker": "SBIN",       "company_name": "State Bank of India",             "exchange": "NSE", "yfinance_symbol": "SBIN.NS"},
    {"ticker": "BHARTIARTL", "company_name": "Bharti Airtel Ltd",               "exchange": "NSE", "yfinance_symbol": "BHARTIARTL.NS"},
    {"ticker": "KOTAKBANK",  "company_name": "Kotak Mahindra Bank Ltd",         "exchange": "NSE", "yfinance_symbol": "KOTAKBANK.NS"},
    {"ticker": "LT",         "company_name": "Larsen & Toubro Ltd",             "exchange": "NSE", "yfinance_symbol": "LT.NS"},
    {"ticker": "AXISBANK",   "company_name": "Axis Bank Ltd",                   "exchange": "NSE", "yfinance_symbol": "AXISBANK.NS"},
    {"ticker": "BAJFINANCE", "company_name": "Bajaj Finance Ltd",               "exchange": "NSE", "yfinance_symbol": "BAJFINANCE.NS"},
    {"ticker": "ASIANPAINT", "company_name": "Asian Paints Ltd",                "exchange": "NSE", "yfinance_symbol": "ASIANPAINT.NS"},
    {"ticker": "MARUTI",     "company_name": "Maruti Suzuki India Ltd",         "exchange": "NSE", "yfinance_symbol": "MARUTI.NS"},
    {"ticker": "SUNPHARMA",  "company_name": "Sun Pharmaceutical Industries",   "exchange": "NSE", "yfinance_symbol": "SUNPHARMA.NS"},
    {"ticker": "TITAN",      "company_name": "Titan Company Ltd",               "exchange": "NSE", "yfinance_symbol": "TITAN.NS"},
    {"ticker": "ULTRACEMCO", "company_name": "UltraTech Cement Ltd",            "exchange": "NSE", "yfinance_symbol": "ULTRACEMCO.NS"},
    {"ticker": "WIPRO",      "company_name": "Wipro Ltd",                       "exchange": "NSE", "yfinance_symbol": "WIPRO.NS"},
    {"ticker": "NESTLEIND",  "company_name": "Nestle India Ltd",                "exchange": "NSE", "yfinance_symbol": "NESTLEIND.NS"},
    {"ticker": "ADANIENT",   "company_name": "Adani Enterprises Ltd",           "exchange": "NSE", "yfinance_symbol": "ADANIENT.NS"},
    {"ticker": "ADANIPORTS", "company_name": "Adani Ports & SEZ Ltd",           "exchange": "NSE", "yfinance_symbol": "ADANIPORTS.NS"},
    {"ticker": "APOLLOHOSP", "company_name": "Apollo Hospitals Enterprise Ltd", "exchange": "NSE", "yfinance_symbol": "APOLLOHOSP.NS"},
    {"ticker": "BAJAJFINSV", "company_name": "Bajaj Finserv Ltd",               "exchange": "NSE", "yfinance_symbol": "BAJAJFINSV.NS"},
    {"ticker": "BEL",        "company_name": "Bharat Electronics Ltd",          "exchange": "NSE", "yfinance_symbol": "BEL.NS"},
    {"ticker": "BPCL",       "company_name": "Bharat Petroleum Corp Ltd",       "exchange": "NSE", "yfinance_symbol": "BPCL.NS"},
    {"ticker": "BRITANNIA",  "company_name": "Britannia Industries Ltd",        "exchange": "NSE", "yfinance_symbol": "BRITANNIA.NS"},
    {"ticker": "CIPLA",      "company_name": "Cipla Ltd",                       "exchange": "NSE", "yfinance_symbol": "CIPLA.NS"},
    {"ticker": "COALINDIA",  "company_name": "Coal India Ltd",                  "exchange": "NSE", "yfinance_symbol": "COALINDIA.NS"},
    {"ticker": "DIVISLAB",   "company_name": "Divi's Laboratories Ltd",         "exchange": "NSE", "yfinance_symbol": "DIVISLAB.NS"},
    {"ticker": "DRREDDY",    "company_name": "Dr. Reddy's Laboratories Ltd",    "exchange": "NSE", "yfinance_symbol": "DRREDDY.NS"},
    {"ticker": "EICHERMOT",  "company_name": "Eicher Motors Ltd",               "exchange": "NSE", "yfinance_symbol": "EICHERMOT.NS"},
    {"ticker": "GRASIM",     "company_name": "Grasim Industries Ltd",           "exchange": "NSE", "yfinance_symbol": "GRASIM.NS"},
    {"ticker": "HCLTECH",    "company_name": "HCL Technologies Ltd",            "exchange": "NSE", "yfinance_symbol": "HCLTECH.NS"},
    {"ticker": "HDFCLIFE",   "company_name": "HDFC Life Insurance Co Ltd",      "exchange": "NSE", "yfinance_symbol": "HDFCLIFE.NS"},
    {"ticker": "HEROMOTOCO", "company_name": "Hero MotoCorp Ltd",               "exchange": "NSE", "yfinance_symbol": "HEROMOTOCO.NS"},
    {"ticker": "INDUSINDBK", "company_name": "IndusInd Bank Ltd",               "exchange": "NSE", "yfinance_symbol": "INDUSINDBK.NS"},
    {"ticker": "JSWSTEEL",   "company_name": "JSW Steel Ltd",                   "exchange": "NSE", "yfinance_symbol": "JSWSTEEL.NS"},
    {"ticker": "M&M",        "company_name": "Mahindra & Mahindra Ltd",         "exchange": "NSE", "yfinance_symbol": "M&M.NS"},
    {"ticker": "NTPC",       "company_name": "NTPC Ltd",                        "exchange": "NSE", "yfinance_symbol": "NTPC.NS"},
    {"ticker": "ONGC",       "company_name": "Oil & Natural Gas Corp Ltd",      "exchange": "NSE", "yfinance_symbol": "ONGC.NS"},
    {"ticker": "POWERGRID",  "company_name": "Power Grid Corp",                 "exchange": "NSE", "yfinance_symbol": "POWERGRID.NS"},
    {"ticker": "SHREECEM",   "company_name": "Shree Cement Ltd",                "exchange": "NSE", "yfinance_symbol": "SHREECEM.NS"},
    {"ticker": "TATACONSUM", "company_name": "Tata Consumer Products Ltd",      "exchange": "NSE", "yfinance_symbol": "TATACONSUM.NS"},
    {"ticker": "TATAMOTORS", "company_name": "Tata Motors Ltd",                 "exchange": "NSE", "yfinance_symbol": "TMCV.NS"},
    {"ticker": "TATASTEEL",  "company_name": "Tata Steel Ltd",                  "exchange": "NSE", "yfinance_symbol": "TATASTEEL.NS"},
    {"ticker": "TECHM",      "company_name": "Tech Mahindra Ltd",               "exchange": "NSE", "yfinance_symbol": "TECHM.NS"},
    {"ticker": "TRENT",      "company_name": "Trent Ltd",                       "exchange": "NSE", "yfinance_symbol": "TRENT.NS"},
    {"ticker": "ETERNAL",    "company_name": "Eternal Ltd",                     "exchange": "NSE", "yfinance_symbol": "ETERNAL.NS"},
    {"ticker": "JIOFIN",     "company_name": "Jio Financial Services Ltd",      "exchange": "NSE", "yfinance_symbol": "JIOFIN.NS"},
    {"ticker": "HAL",        "company_name": "Hindustan Aeronautics Ltd",       "exchange": "NSE", "yfinance_symbol": "HAL.NS"},
    {"ticker": "SIEMENS",    "company_name": "Siemens Ltd",                     "exchange": "NSE", "yfinance_symbol": "SIEMENS.NS"},
    {"ticker": "ABB",        "company_name": "ABB India Ltd",                   "exchange": "NSE", "yfinance_symbol": "ABB.NS"},
    {"ticker": "PIDILITIND", "company_name": "Pidilite Industries Ltd",         "exchange": "NSE", "yfinance_symbol": "PIDILITIND.NS"},
    {"ticker": "DABUR",      "company_name": "Dabur India Ltd",                 "exchange": "NSE", "yfinance_symbol": "DABUR.NS"},
    {"ticker": "DMART",      "company_name": "Avenue Supermarts Ltd",           "exchange": "NSE", "yfinance_symbol": "DMART.NS"},
    {"ticker": "GODREJCP",   "company_name": "Godrej Consumer Products Ltd",    "exchange": "NSE", "yfinance_symbol": "GODREJCP.NS"},
    {"ticker": "LUPIN",      "company_name": "Lupin Ltd",                       "exchange": "NSE", "yfinance_symbol": "LUPIN.NS"},
    {"ticker": "MOTHERSON",  "company_name": "Samvardhana Motherson International Ltd", "exchange": "NSE", "yfinance_symbol": "MOTHERSON.NS"},
    {"ticker": "PFC",        "company_name": "Power Finance Corporation Ltd",   "exchange": "NSE", "yfinance_symbol": "PFC.NS"},
    {"ticker": "RECLTD",     "company_name": "REC Ltd",                         "exchange": "NSE", "yfinance_symbol": "RECLTD.NS"},
    {"ticker": "TVSMOTOR",   "company_name": "TVS Motor",                       "exchange": "NSE", "yfinance_symbol": "TVSMOTOR.NS"},
    {"ticker": "VEDL",       "company_name": "Vedanta Ltd",                     "exchange": "NSE", "yfinance_symbol": "VEDL.NS"},
    {"ticker": "BANKBARODA", "company_name": "Bank of Baroda",                  "exchange": "NSE", "yfinance_symbol": "BANKBARODA.NS"},
    {"ticker": "CANBK",      "company_name": "Canara Bank",                     "exchange": "NSE", "yfinance_symbol": "CANBK.NS"},
    {"ticker": "IOC",        "company_name": "Indian Oil Corp",                 "exchange": "NSE", "yfinance_symbol": "IOC.NS"},
    {"ticker": "GAIL",       "company_name": "GAIL India Ltd",                  "exchange": "NSE", "yfinance_symbol": "GAIL.NS"},
    {"ticker": "HAVELLS",    "company_name": "Havells India Ltd",               "exchange": "NSE", "yfinance_symbol": "HAVELLS.NS"},
    {"ticker": "BOSCHLTD",   "company_name": "Bosch Ltd",                       "exchange": "NSE", "yfinance_symbol": "BOSCHLTD.NS"},
    {"ticker": "BHEL",       "company_name": "BHEL",                            "exchange": "NSE", "yfinance_symbol": "BHEL.NS"},
    {"ticker": "COLPAL",     "company_name": "Colgate Palmolive India",         "exchange": "NSE", "yfinance_symbol": "COLPAL.NS"},
    {"ticker": "CUMMINSIND", "company_name": "Cummins India Ltd",               "exchange": "NSE", "yfinance_symbol": "CUMMINSIND.NS"},
    {"ticker": "AMBUJACEM",  "company_name": "Ambuja Cements Ltd",              "exchange": "NSE", "yfinance_symbol": "AMBUJACEM.NS"},
    {"ticker": "ACC",        "company_name": "ACC Ltd",                         "exchange": "NSE", "yfinance_symbol": "ACC.NS"},
    {"ticker": "AUROPHARMA", "company_name": "Aurobindo Pharma Ltd",            "exchange": "NSE", "yfinance_symbol": "AUROPHARMA.NS"},
    {"ticker": "BIOCON",     "company_name": "Biocon Ltd",                      "exchange": "NSE", "yfinance_symbol": "BIOCON.NS"},
    {"ticker": "ICICIPRULI", "company_name": "ICICI Prudential Life",           "exchange": "NSE", "yfinance_symbol": "ICICIPRULI.NS"},
    {"ticker": "SBILIFE",    "company_name": "SBI Life",                        "exchange": "NSE", "yfinance_symbol": "SBILIFE.NS"},
    {"ticker": "ICICIGI",    "company_name": "ICICI Lombard",                   "exchange": "NSE", "yfinance_symbol": "ICICIGI.NS"},
    {"ticker": "TORNTPHARM", "company_name": "Torrent Pharma",                  "exchange": "NSE", "yfinance_symbol": "TORNTPHARM.NS"},
    {"ticker": "VOLTAS",     "company_name": "Voltas Ltd",                      "exchange": "NSE", "yfinance_symbol": "VOLTAS.NS"},
    {"ticker": "ZYDUSLIFE",  "company_name": "Zydus Lifesciences",              "exchange": "NSE", "yfinance_symbol": "ZYDUSLIFE.NS"},
    {"ticker": "IRCTC",      "company_name": "IRCTC",                           "exchange": "NSE", "yfinance_symbol": "IRCTC.NS"},
    {"ticker": "IRFC",       "company_name": "IRFC",                            "exchange": "NSE", "yfinance_symbol": "IRFC.NS"},
    {"ticker": "RVNL",       "company_name": "RVNL",                            "exchange": "NSE", "yfinance_symbol": "RVNL.NS"},
    {"ticker": "NHPC",       "company_name": "NHPC",                            "exchange": "NSE", "yfinance_symbol": "NHPC.NS"},
    {"ticker": "SAIL",       "company_name": "SAIL",                            "exchange": "NSE", "yfinance_symbol": "SAIL.NS"},
    {"ticker": "UNIONBANK",  "company_name": "Union Bank",                      "exchange": "NSE", "yfinance_symbol": "UNIONBANK.NS"},
    {"ticker": "FEDERALBNK", "company_name": "Federal Bank",                    "exchange": "NSE", "yfinance_symbol": "FEDERALBNK.NS"},
    {"ticker": "PNB",        "company_name": "Punjab National Bank",            "exchange": "NSE", "yfinance_symbol": "PNB.NS"},
    {"ticker": "INDIGO",     "company_name": "InterGlobe Aviation",             "exchange": "NSE", "yfinance_symbol": "INDIGO.NS"},
    {"ticker": "PAGEIND",    "company_name": "Page Industries",                 "exchange": "NSE", "yfinance_symbol": "PAGEIND.NS"},
    {"ticker": "MRF",        "company_name": "MRF Ltd",                         "exchange": "NSE", "yfinance_symbol": "MRF.NS"},
    {"ticker": "ESCORTS",    "company_name": "Escorts Kubota",                  "exchange": "NSE", "yfinance_symbol": "ESCORTS.NS"},
    {"ticker": "GLENMARK",   "company_name": "Glenmark Pharma",                 "exchange": "NSE", "yfinance_symbol": "GLENMARK.NS"},
    {"ticker": "MPHASIS",    "company_name": "Mphasis Ltd",                     "exchange": "NSE", "yfinance_symbol": "MPHASIS.NS"},
    {"ticker": "PERSISTENT", "company_name": "Persistent Systems",              "exchange": "NSE", "yfinance_symbol": "PERSISTENT.NS"},
    {"ticker": "COFORGE",    "company_name": "Coforge Ltd",                     "exchange": "NSE", "yfinance_symbol": "COFORGE.NS"},
    {"ticker": "LTIM",       "company_name": "LTIMindtree",                     "exchange": "NSE", "yfinance_symbol": "LTM.NS"},
    {"ticker": "OFSS",       "company_name": "Oracle Financial Services Software","exchange": "NSE", "yfinance_symbol": "OFSS.NS"},
    {"ticker": "NYKAA",      "company_name": "FSN E-Commerce Ventures",         "exchange": "NSE", "yfinance_symbol": "NYKAA.NS"},
    {"ticker": "PAYTM",      "company_name": "One97 Communications",            "exchange": "NSE", "yfinance_symbol": "PAYTM.NS"},
    {"ticker": "POLYCAB",    "company_name": "Polycab India",                   "exchange": "NSE", "yfinance_symbol": "POLYCAB.NS"},
    {"ticker": "ASTRAL",     "company_name": "Astral Ltd",                      "exchange": "NSE", "yfinance_symbol": "ASTRAL.NS"},
    {"ticker": "MSFT",       "company_name": "Microsoft Corporation",           "exchange": "NASDAQ", "yfinance_symbol": "MSFT"},
]